version: '3.4'
services:
  server:
    build: avitly/
    ports:
      - "9000:9000"
    restart: always
    depends_on:
      - postgres
    environment:
      - DATABASE_URL=postgresql://postgres:avitopass@autopostgres:5432/avitoauto
      - HTTP_PORT=:9000
      - LOG_LEVEL=TRACE
      - TIME_TO_SHUTDOWN=10
    volumes:
    - ./logs/:/root/logs/
    stop_signal: SIGINT
    stop_grace_period: 15s
  postgres:
    container_name: autopostgres
    build: postgres/
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - "5555:5432"

